apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mplatteau
  name: mongo-express-deployment
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express:latest
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongodb-username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongodb-password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: mongodb-configmap # fait référence à l'élément ConfigMap créé précédemment
              key: database_url

---

apiVersion: v1
kind: Service
metadata:
  namespace: mplatteau
  name: mongo-express-service
  labels:
    app: mongo-express
spec:
  selector:
    app: mongo-express
  type: LoadBalancer # pour exposer le service en dehors du cluster
  ports: 
    - port: 8081 # port exposé par le service, à vérifier sur l'image mongo-express dans dockerhub
      targetPort: 8081