apiVersion: v1
kind: Secret
metadata:
  namespace: mplatteau 
  name: mongodb-secret
  labels:
    app: mongodb
type: Opaque
stringData:
  mongodb-username: user
  mongodb-password: password

